"use client";
import { FormEvent, useState } from "react";

type Precision="exact"|"approximate"|"unknown";
export function ReaderConsole(){
  const [precision,setPrecision]=useState<Precision>("exact");const [result,setResult]=useState<unknown>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError(null);const f=new FormData(e.currentTarget);const payload={full_name:String(f.get("full_name")||""),date_of_birth:String(f.get("date_of_birth")||""),birth_time:precision==="unknown"?null:String(f.get("birth_time")||""),birth_time_precision:precision,birthplace_label:String(f.get("birthplace_label")||""),latitude:Number(f.get("latitude")),longitude:Number(f.get("longitude")),timezone:String(f.get("timezone")||"Asia/Kolkata")};try{const path=precision==="unknown"?"/api/astrology/unknown-time":"/api/astrology/chart";const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Calculation failed");setResult(j)}catch(err){setError(err instanceof Error?err.message:"Calculation failed")}finally{setBusy(false)}}
  return <section className="readerGrid"><form className="panel form" onSubmit={submit}><label>Full name<input name="full_name" required/></label><label>Date of birth<input name="date_of_birth" type="date" required/></label><label>Birth time precision<select value={precision} onChange={e=>setPrecision(e.target.value as Precision)}><option value="exact">Exact</option><option value="approximate">Approximate</option><option value="unknown">Unknown</option></select></label>{precision!=="unknown"&&<label>Birth time<input name="birth_time" type="time" required/></label>}<label>Birthplace<input name="birthplace_label" placeholder="Bhilai, Chhattisgarh, India" required/></label><div className="two"><label>Latitude<input name="latitude" type="number" step="any" required/></label><label>Longitude<input name="longitude" type="number" step="any" required/></label></div><label>Timezone<input name="timezone" defaultValue="Asia/Kolkata" required/></label><button disabled={busy}>{busy?"Calculating…":"Calculate"}</button>{error&&<p className="error">{error}</p>}</form><article className="panel result"><h2>Calculation output</h2>{result?<pre>{JSON.stringify(result,null,2)}</pre>:<p>No calculation yet.</p>}</article></section>
}
